import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigrations1703202916002 implements MigrationInterface {
  public readonly name = 'AutoGeneratedMigrations1703202916002'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "order_product" DROP CONSTRAINT "FK_073c85ed133e05241040bd70f02"`);
    await queryRunner.query(`ALTER TABLE "order_product" DROP CONSTRAINT "FK_3fb066240db56c9558a91139431"`);
    await queryRunner.query(`ALTER TABLE "order_product" ALTER COLUMN "productId" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "order_product" ALTER COLUMN "orderId" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "order_product" ADD CONSTRAINT "FK_3fb066240db56c9558a91139431" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "order_product" ADD CONSTRAINT "FK_073c85ed133e05241040bd70f02" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
  }

  public async down(): Promise<void> {
    return;
  }
}
