import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGeneratedMigrations1703171135619 implements MigrationInterface {
  public readonly name = 'AutoGeneratedMigrations1703171135619'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email")`);
  }

  public async down(): Promise<void> {
    return;
  }
}
