import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGeneratedMigrations1703190067911 implements MigrationInterface {
  public readonly name = 'AutoGeneratedMigrations1703190067911'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "temporary_password" DROP COLUMN "expiresAt"`);
    await queryRunner.query(`ALTER TABLE "temporary_password" ADD "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
  }

  public async down(): Promise<void> {
    return;    
  }
}
