import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigrations1703202708850 implements MigrationInterface {
  public readonly name = 'AutoGeneratedMigrations1703202708850'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "order_product" DROP CONSTRAINT "FK_3fb066240db56c9558a91139431"`);
    await queryRunner.query(`ALTER TABLE "order_product" ADD CONSTRAINT "FK_3fb066240db56c9558a91139431" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
  }

  public async down(): Promise<void> {
    return;
  }
}
